CREATE OR REPLACE VIEW public.combined_chr_analytic AS
 SELECT a._5_digit_fips,
    a.premature_death_aian,
    a.premature_death_asian_pacific_islander,
    a.premature_death_black,
    a.premature_death_hispanic,
    a.premature_death_white,
    a.premature_death_nhopi,
    a.poor_or_fair_health_raw_value,
    a.poor_physical_health_days_raw_value,
    a.poor_mental_health_days_raw_value,
    a.food_environment_index_raw_value,
    a.uninsured_raw_value,
    a.preventable_hospital_stays_raw_value,
    a.ratio_of_population_to_mental_health_providers,
    a.preventable_hospital_stays_black,
    a.preventable_hospital_stays_hispanic,
    a.preventable_hospital_stays_white,
    a.flu_vaccinations_raw_value,
    a.high_school_completion_raw_value,
    a.some_college_raw_value,
    a.unemployment_raw_value,
    a.children_in_poverty_raw_value,
    a.children_in_poverty_black,
    a.children_in_poverty_hispanic,
    a.children_in_poverty_white,
    b.income_inequality_raw_value,
    b.injury_deaths_raw_value,
    b.severe_housing_problems_raw_value,
    b.percentage_of_households_with_overcrowding,
    b.pct_households_with_lack_of_kitchen_or_plumbing,
    b.life_expectancy_raw_value,
    b.premature_age_adjusted_mortality_raw_value,
    b.infant_mortality_white,
    b.infant_mortality_black,
    b.infant_mortality_hispanic,
    b.food_insecurity_raw_value,
    c.uninsured_adults_raw_value,
    c.uninsured_children_raw_value,
    c.ratio_of_population_to_primary_care_providers_other_than_physic,
    c.high_school_graduation_raw_value,
    c.gender_pay_gap_raw_value,
    c.median_household_income_raw_value,
    c.broadband_access_raw_value,
    c.below_18_years_of_age_raw_value,
    c._65_and_older_raw_value,
    c.non_hispanic_black_raw_value,
    c.american_indian_or_alaska_native_raw_value,
    c.asian_raw_value,
    c.native_hawaiian_or_other_pacific_islander_raw_value,
    c.hispanic_raw_value,
    c.non_hispanic_white_raw_value,
    c.not_proficient_in_english_raw_value,
    c.female_raw_value
   FROM chr_analytic_chunk_1 a
     FULL JOIN chr_analytic_chunk_2 b ON a._5_digit_fips::text = b._5_digit_fips::text
     FULL JOIN chr_analytic_chunk_3 c ON a._5_digit_fips::text = c._5_digit_fips::text
  WHERE a._5_digit_fips::text !~~ '%000'::text;;
