CREATE OR REPLACE VIEW public."vw_hospital_level_aipw" AS
 SELECT cw.aha_id,
    cw.cms_facility_id,
    cw.aha_county_fips,
    idx.social_economic_factors_score,
    idx.health_behaviors_score,
    idx.physical_environment_score,
    idx.medicaid_expansion_active,
    idx.avg_patient_services_margin,
    idx.health_outcomes_score,
    idx.clinical_care_score,
    idx.weighted_ai_adoption_score,
    idx.weighted_robotics_adoption_score,
    idx.population,
    idx.census_division,
    perf.bsc,
    perf.robohos,
    perf.robosys,
    perf.roboven,
    perf.adjpd,
    perf.wfaipsn,
    perf.wfaippd,
    perf.wfaiss,
    perf.wfaiart,
    perf.wfaioacw,
    perf.facility_name,
    perf.address,
    perf.city_town,
    perf.state,
    perf.zip_code,
    perf.county_parish,
    perf.telephone_number,
    perf.psi_90_score,
    perf.comp_hip_knee_score,
    perf.mort_30_ami_score,
    perf.mort_30_cabg_score,
    perf.mort_30_copd_score,
    perf.mort_30_hf_score,
    perf.mort_30_pn_score,
    perf.mort_30_stk_score,
    perf.psi_03_score,
    perf.psi_04_score,
    perf.psi_06_score,
    perf.psi_08_score,
    perf.psi_09_score,
    perf.psi_10_score,
    perf.psi_11_score,
    perf.psi_12_score,
    perf.psi_13_score,
    perf.psi_14_score,
    perf.psi_15_score,
    gen.hospital_type,
    gen.hospital_ownership,
    inf.hai_3_cilower_score,
    inf.hai_6_eligcases_score,
    inf.hai_2_eligcases_score,
    inf.hai_1_eligcases_score,
    inf.hai_4_ciupper_score,
    inf.hai_1_numerator_score,
    inf.hai_5_dopc_score,
    inf.hai_6_dopc_score,
    inf.hai_6_cilower_score,
    inf.hai_5_sir_score,
    inf.hai_4_eligcases_score,
    inf.hai_5_eligcases_score,
    inf.hai_4_numerator_score,
    inf.hai_6_sir_score,
    inf.hai_5_ciupper_score,
    inf.hai_2_numerator_score,
    inf.hai_6_ciupper_score,
    inf.hai_4_dopc_score,
    inf.hai_5_numerator_score,
    inf.hai_1_sir_score,
    inf.hai_4_cilower_score,
    inf.hai_3_sir_score,
    inf.hai_2_dopc_score,
    inf.hai_4_sir_score,
    inf.hai_6_numerator_score,
    inf.hai_2_ciupper_score,
    inf.hai_3_ciupper_score,
    inf.hai_2_sir_score,
    inf.hai_1_cilower_score,
    inf.hai_2_cilower_score,
    inf.hai_3_eligcases_score,
    inf.hai_3_numerator_score,
    inf.hai_5_cilower_score,
    inf.hai_1_dopc_score,
    inf.hai_3_dopc_score,
    inf.hai_1_ciupper_score,
    pe."H_BATH_HELP_A_P" AS h_bath_help_a_p,
    pe."H_BATH_HELP_SN_P" AS h_bath_help_sn_p,
    pe."H_BATH_HELP_U_P" AS h_bath_help_u_p,
    pe."H_CALL_BUTTON_A_P" AS h_call_button_a_p,
    pe."H_CALL_BUTTON_SN_P" AS h_call_button_sn_p,
    pe."H_CALL_BUTTON_U_P" AS h_call_button_u_p,
    pe."H_CLEAN_HSP_A_P" AS h_clean_hsp_a_p,
    pe."H_CLEAN_HSP_SN_P" AS h_clean_hsp_sn_p,
    pe."H_CLEAN_HSP_U_P" AS h_clean_hsp_u_p,
    pe."H_CLEAN_LINEAR_SCORE" AS h_clean_linear_score,
    pe."H_CLEAN_STAR_RATING" AS h_clean_star_rating,
    pe."H_COMP_1_A_P" AS h_comp_1_a_p,
    pe."H_COMP_1_LINEAR_SCORE" AS h_comp_1_linear_score,
    pe."H_COMP_1_SN_P" AS h_comp_1_sn_p,
    pe."H_COMP_1_STAR_RATING" AS h_comp_1_star_rating,
    pe."H_COMP_1_U_P" AS h_comp_1_u_p,
    pe."H_COMP_2_A_P" AS h_comp_2_a_p,
    pe."H_COMP_2_LINEAR_SCORE" AS h_comp_2_linear_score,
    pe."H_COMP_2_SN_P" AS h_comp_2_sn_p,
    pe."H_COMP_2_STAR_RATING" AS h_comp_2_star_rating,
    pe."H_COMP_2_U_P" AS h_comp_2_u_p,
    pe."H_COMP_3_A_P" AS h_comp_3_a_p,
    pe."H_COMP_3_LINEAR_SCORE" AS h_comp_3_linear_score,
    pe."H_COMP_3_SN_P" AS h_comp_3_sn_p,
    pe."H_COMP_3_STAR_RATING" AS h_comp_3_star_rating,
    pe."H_COMP_3_U_P" AS h_comp_3_u_p,
    pe."H_COMP_5_A_P" AS h_comp_5_a_p,
    pe."H_COMP_5_LINEAR_SCORE" AS h_comp_5_linear_score,
    pe."H_COMP_5_SN_P" AS h_comp_5_sn_p,
    pe."H_COMP_5_STAR_RATING" AS h_comp_5_star_rating,
    pe."H_COMP_5_U_P" AS h_comp_5_u_p,
    pe."H_COMP_6_LINEAR_SCORE" AS h_comp_6_linear_score,
    pe."H_COMP_6_N_P" AS h_comp_6_n_p,
    pe."H_COMP_6_STAR_RATING" AS h_comp_6_star_rating,
    pe."H_COMP_6_Y_P" AS h_comp_6_y_p,
    pe."H_COMP_7_A" AS h_comp_7_a,
    pe."H_COMP_7_D_SD" AS h_comp_7_d_sd,
    pe."H_COMP_7_LINEAR_SCORE" AS h_comp_7_linear_score,
    pe."H_COMP_7_SA" AS h_comp_7_sa,
    pe."H_COMP_7_STAR_RATING" AS h_comp_7_star_rating,
    pe."H_CT_MED_A" AS h_ct_med_a,
    pe."H_CT_MED_D_SD" AS h_ct_med_d_sd,
    pe."H_CT_MED_SA" AS h_ct_med_sa,
    pe."H_CT_PREFER_A" AS h_ct_prefer_a,
    pe."H_CT_PREFER_D_SD" AS h_ct_prefer_d_sd,
    pe."H_CT_PREFER_SA" AS h_ct_prefer_sa,
    pe."H_CT_UNDER_A" AS h_ct_under_a,
    pe."H_CT_UNDER_D_SD" AS h_ct_under_d_sd,
    pe."H_CT_UNDER_SA" AS h_ct_under_sa,
    pe."H_DISCH_HELP_N_P" AS h_disch_help_n_p,
    pe."H_DISCH_HELP_Y_P" AS h_disch_help_y_p,
    pe."H_DOCTOR_EXPLAIN_A_P" AS h_doctor_explain_a_p,
    pe."H_DOCTOR_EXPLAIN_SN_P" AS h_doctor_explain_sn_p,
    pe."H_DOCTOR_EXPLAIN_U_P" AS h_doctor_explain_u_p,
    pe."H_DOCTOR_LISTEN_A_P" AS h_doctor_listen_a_p,
    pe."H_DOCTOR_LISTEN_SN_P" AS h_doctor_listen_sn_p,
    pe."H_DOCTOR_LISTEN_U_P" AS h_doctor_listen_u_p,
    pe."H_DOCTOR_RESPECT_A_P" AS h_doctor_respect_a_p,
    pe."H_DOCTOR_RESPECT_SN_P" AS h_doctor_respect_sn_p,
    pe."H_DOCTOR_RESPECT_U_P" AS h_doctor_respect_u_p,
    pe."H_HSP_RATING_0_6" AS h_hsp_rating_0_6,
    pe."H_HSP_RATING_7_8" AS h_hsp_rating_7_8,
    pe."H_HSP_RATING_9_10" AS h_hsp_rating_9_10,
    pe."H_HSP_RATING_LINEAR_SCORE" AS h_hsp_rating_linear_score,
    pe."H_HSP_RATING_STAR_RATING" AS h_hsp_rating_star_rating,
    pe."H_MED_FOR_A_P" AS h_med_for_a_p,
    pe."H_MED_FOR_SN_P" AS h_med_for_sn_p,
    pe."H_MED_FOR_U_P" AS h_med_for_u_p,
    pe."H_NURSE_EXPLAIN_A_P" AS h_nurse_explain_a_p,
    pe."H_NURSE_EXPLAIN_SN_P" AS h_nurse_explain_sn_p,
    pe."H_NURSE_EXPLAIN_U_P" AS h_nurse_explain_u_p,
    pe."H_NURSE_LISTEN_A_P" AS h_nurse_listen_a_p,
    pe."H_NURSE_LISTEN_SN_P" AS h_nurse_listen_sn_p,
    pe."H_NURSE_LISTEN_U_P" AS h_nurse_listen_u_p,
    pe."H_NURSE_RESPECT_A_P" AS h_nurse_respect_a_p,
    pe."H_NURSE_RESPECT_SN_P" AS h_nurse_respect_sn_p,
    pe."H_NURSE_RESPECT_U_P" AS h_nurse_respect_u_p,
    pe."H_QUIET_HSP_A_P" AS h_quiet_hsp_a_p,
    pe."H_QUIET_HSP_SN_P" AS h_quiet_hsp_sn_p,
    pe."H_QUIET_HSP_U_P" AS h_quiet_hsp_u_p,
    pe."H_QUIET_LINEAR_SCORE" AS h_quiet_linear_score,
    pe."H_QUIET_STAR_RATING" AS h_quiet_star_rating,
    pe."H_RECMND_DN" AS h_recmnd_dn,
    pe."H_RECMND_DY" AS h_recmnd_dy,
    pe."H_RECMND_LINEAR_SCORE" AS h_recmnd_linear_score,
    pe."H_RECMND_PY" AS h_recmnd_py,
    pe."H_RECMND_STAR_RATING" AS h_recmnd_star_rating,
    pe."H_SIDE_EFFECTS_A_P" AS h_side_effects_a_p,
    pe."H_SIDE_EFFECTS_SN_P" AS h_side_effects_sn_p,
    pe."H_SIDE_EFFECTS_U_P" AS h_side_effects_u_p,
    pe."H_STAR_RATING" AS h_star_rating,
    pe."H_SYMPTOMS_N_P" AS h_symptoms_n_p,
    pe."H_SYMPTOMS_Y_P" AS h_symptoms_y_p,
    up.readm_30_cabg,
    up.readm_30_hf,
    up.op_35_ed,
    up.op_36,
    up.op_32,
    up.edac_30_ami,
    up.op_35_adm,
    up.readm_30_copd,
    up.readm_30_pn,
    up.readm_30_ami,
    up.readm_30_hip_knee,
    up.readm_30_hosp_wide,
    up.edac_30_pn,
    up.edac_30_hf,
    pch.pch_31,
    pch.pch_37,
    pch.pch_36,
    pch.pch_30,
    te.ef1 AS op_29,
    te.ef2 AS op_23,
    te.ef3 AS op_18c,
    te.ef4 AS stk_02,
    te.ef5 AS hh_02,
    te.ef6 AS op_18b,
    te.ef7 AS op_22,
    te.ef8 AS sev_sep_6hr,
    te.ef9 AS stk_03,
    te.ef10 AS op_40,
    te.ef11 AS ed_2_strata_1,
    te.ef12 AS safe_use_of_opioids,
    te.ef13 AS stk_05,
    te.ef14 AS stk_06,
    te.ef15 AS sev_sep_3hr,
    te.ef16 AS imm_3,
    te.ef17 AS sep_sh_3hr,
    te.ef18 AS hcp_covid_19,
    te.ef19 AS hh_01,
    te.ef20 AS op_31,
    te.ef21 AS vte_2,
    te.ef22 AS edv,
    te.ef23 AS sep_1,
    te.ef24 AS sep_sh_6hr,
    te.ef25 AS vte_1,
    te.ef26 AS ed_2_strata_2
   FROM aha_cms_crosswalk cw
     LEFT JOIN vw_conceptual_model_adjpd idx ON cw.aha_county_fips = idx.county_fips
     LEFT JOIN vw_hospital_performance_metrics perf ON cw.aha_id = perf.aha_id::text
     LEFT JOIN nber_hospital_general_information gen ON cw.cms_facility_id = gen.facility_id::text
     LEFT JOIN vw_healthcare_associated_infections inf ON cw.cms_facility_id = inf.cms_facility_id
     LEFT JOIN vw_hospital_patient_experience pe ON cw.aha_id = pe.aha_id::text
     LEFT JOIN vw_unplanned_hospital_visits up ON cw.cms_facility_id = up.cms_facility_id
     LEFT JOIN ( SELECT nber_pch_complications_unplanned_hosp_visits.facility_id,
            max(
                CASE
                    WHEN nber_pch_complications_unplanned_hosp_visits.measure_id::text = 'PCH-31'::text THEN nber_pch_complications_unplanned_hosp_visits.rate
                    ELSE NULL::character varying
                END::text) AS pch_31,
            max(
                CASE
                    WHEN nber_pch_complications_unplanned_hosp_visits.measure_id::text = 'PCH-37'::text THEN nber_pch_complications_unplanned_hosp_visits.rate
                    ELSE NULL::character varying
                END::text) AS pch_37,
            max(
                CASE
                    WHEN nber_pch_complications_unplanned_hosp_visits.measure_id::text = 'PCH-36'::text THEN nber_pch_complications_unplanned_hosp_visits.rate
                    ELSE NULL::character varying
                END::text) AS pch_36,
            max(
                CASE
                    WHEN nber_pch_complications_unplanned_hosp_visits.measure_id::text = 'PCH-30'::text THEN nber_pch_complications_unplanned_hosp_visits.rate
                    ELSE NULL::character varying
                END::text) AS pch_30
           FROM nber_pch_complications_unplanned_hosp_visits
          GROUP BY nber_pch_complications_unplanned_hosp_visits.facility_id) pch ON cw.cms_facility_id = pch.facility_id::text
     LEFT JOIN vw_timely_effective_care te ON cw.cms_facility_id = te.cms_facility_id;
